### PR TITLE
Added List Views To App

### LINKED ISSUE #3: feat: ListViews
Try to build the UI of the first page using **ListViews**. Adjust the Scrollable physics and place the search bar at the top. We have to have an App Bar in the App so should account for that. Be Innovative

### PR DESCRIPTION
**Pull request by riturajjain2000**
### What is the change?
Added list view to main screen

### What does it fix/add?
Fixes #3 

### How was it tested?
Debugged and Tested with Android Studio an Android Emulator

## Submissions guide:
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/raghavSharma1472/RecipeBookFlutter/issues) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you lint your code locally prior to submission?

### Screenshots (if appropriate):
Screenshot_1607507313
Screenshot_1607507309
to APP

### CODE REVIEW

**Comment by raghavSharma1472** [comment]
@riturajjain2000 I would really appreciate if you could please display the ingredients part in list with bullets or number instead of paragraph. Secondly, this app is not for selling anything so _maybe_ you can remove the "Order Now" Option and in the main page where you show the price of each dish, you can replace it with the sign of _veg/non veg_ .

**Comment by riturajjain2000** [comment]
> @riturajjain2000 I would really appreciate if you could please display the ingredients part in list with bullets or number instead of paragraph. Secondly, this app is not for selling anything so _maybe_ you can remove the "Order Now" Option and in the main page where you show the price of each dish, you can replace it with the sign of _veg/non veg_ .

Ok sure !!

**Review by littleironical — COMMENTED** [review]
It would be good if you change the variable names to `custom_<color-name>` instead of `kBackgroundColor` inside `lib/constants.dart`. 
You can't guess the color with it's color code, right.

**Comment by riturajjain2000** [comment]
> It would be good if you change the variable names to `custom_<color-name>` instead of `kBackgroundColor` inside `lib/constants.dart`.
> You can't guess the color with it's color code, right.

ok

**Comment by riturajjain2000** [comment]
Changes Done ,
Screenshot_1607524459

Screenshot_1607524462

**Review by raghavSharma1472 — APPROVED** [review]

**Review by littleironical — COMMENTED** [review]
Looking great 👍

**Pull request merged**
