### PR TITLE
docs: Readme Updation

### LINKED ISSUE #6: docs:Readme Updation
The current Readme file is very suttle and is hard for beginners to get stared .
So can I improve it making it more attractive, adding images and adding a getting started guide

### PR DESCRIPTION
**Pull request by Tejas1510**
@raghavSharma1472 Sir I have made changes in the Readme
Please give it a look

### CODE REVIEW

**Comment by raghavSharma1472** [comment]
Can you also please include "Rules and Scoring System" and "FAQ" here from https://github.com/NJACKWinterOfCode/Get-Started-NWoC20 Readme

**Comment by Tejas1510** [comment]
Sure

**Comment by Tejas1510** [comment]
@raghavSharma1472 I have added  "Rules and Scoring System" and "FAQ"

**Review by raghavSharma1472 — APPROVED** [review]

**Comment by Tejas1510** [comment]
Sir can you update the leaderboard with points earned for the pull request

**Comment by raghavSharma1472** [comment]
Already did you can check

**Comment by Tejas1510** [comment]
Thanks a lot sir
Would love to contribute more on the project

**Pull request merged**
