### PR TITLE
Adding pull request template

### LINKED ISSUE #14: Docs: Add pull request template
**Is your feature request related to a problem? Please describe.**
Sometimes pull requests are not well written and are not easily comprehensible. Some people send pull request without stating the issue they are solving.

**Describe the solution you'd like**
Make a pull request template so that we can ensure better workflow and get the required information about pr from a contributor.

**Describe alternatives you've considered**
I considered the alternative of making contributing.md file. However, it is easy for a person to forget the guidelines there. Moreover by providing essential checklist while pr can help to avoid merge conflicts later on. 

**Approach to be followed (optional)**

1. Make a template suitable for PR requests.
2. Add a checklist of essential items to consider before submitting the pull requests.

**Additional context (optional)**
Can I work on this issue?

### PR DESCRIPTION
**Pull request by KerinPithawala**
Fixes issue #14 
Kindly review my PR

### CODE REVIEW

**Review by raghavSharma1472 — APPROVED** [review]

**Comment by KerinPithawala** [comment]
Could you add this pr for NWoC?

**Comment by raghavSharma1472** [comment]
Yeah I updated the score in the sheet, as far as the PR labelling is considered that actually is not required as I already labeled the issue and linked the issue with the PR

**Review by littleironical — COMMENTED** [review]
is it necessary to create a new branch?

**Comment by KerinPithawala** [comment]
I just added new branch because if any changes is required or some errors arises then one branch shouldn’t affect all others. 😅

**Pull request merged**
